[package]
name = "ganttchart"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
async-graphql = "4.0"
async-graphql-actix-web = "4.0"
clap = { version = "4.0.23", features = ["derive"] }
